// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZ_CrozrOYB-wXnZfgJotLUSePlZ-lRw',
    appId: '1:896102639664:web:3974f6fa279648a659e5f5',
    messagingSenderId: '896102639664',
    projectId: 'signlang-b7934',
    authDomain: 'signlang-b7934.firebaseapp.com',
    storageBucket: 'signlang-b7934.appspot.com',
    measurementId: 'G-WBLT5VNM0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwVTeVSxHuEc6WnQmv7w0aFPrXvmRJmo',
    appId: '1:896102639664:android:75b967fb0894493859e5f5',
    messagingSenderId: '896102639664',
    projectId: 'signlang-b7934',
    storageBucket: 'signlang-b7934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs8FzkbY48BdwOYgkqEtU61m0TOeqyAKU',
    appId: '1:896102639664:ios:b1d58f481af02f2659e5f5',
    messagingSenderId: '896102639664',
    projectId: 'signlang-b7934',
    storageBucket: 'signlang-b7934.appspot.com',
    iosClientId: '896102639664-9ga3d79524c3v2dljulp131cj3qdiph2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs8FzkbY48BdwOYgkqEtU61m0TOeqyAKU',
    appId: '1:896102639664:ios:b1d58f481af02f2659e5f5',
    messagingSenderId: '896102639664',
    projectId: 'signlang-b7934',
    storageBucket: 'signlang-b7934.appspot.com',
    iosClientId: '896102639664-9ga3d79524c3v2dljulp131cj3qdiph2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
